### ISSUE TITLE
抱歉打扰了，导入您的应用，

### ISSUE THREAD

**Issue by lipokli** [donlan/Tuyi#15]
导入应用 设置环信和bmobKEY之后，应用不能同步用户数据
logcat：  2109-2245/dong.lan.tuyi E/smile: BmobJNI-->aes:doFinal has error     
注册新用户 bmob后端数据库有写入  但是应用不能正常使用
我看您的parse包里使用了环信parse  目前官网已经停止这个服务了，是否与此有关呢，关于替换您有什么建议吗  
麻烦您了  谢谢

**Comment by donlan** [comment]
因为使用了很久之前的环信IM SDK，现在他们应该不支持很早之前的版本了。
替换的话，估计成本很大。更新到环信IM SDK V3.0之后的版本的话，估计需要重构。

很久不维护这个项目了，实在抱歉
